# DEV:
# docker compose build
# PROD:
# docker compose -f compose.yml -f compose.prod.yml build
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - bsn_shared_data:/var/www/bsn
    expose:
      - "9000"  # php-fpm
    environment:
      MARIADB_DATABASE: app_db
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_pass
    env_file:
      - .env
    depends_on:
      - db
      - cache
      - mongo

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "44077:80"
    depends_on:
      - app
    volumes:
      - bsn_shared_data:/var/www/bsn

  adminer:
    image: adminer
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      - db

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongo_pass}
      MONGO_INITDB_DATABASE: ${MONGO_BASENAME:-app_db}
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_PORT: 3306
      MARIADB_ROOT_PASSWORD: n4dfN3asI5wLPkXx1Yqg
      MARIADB_DATABASE: app_db
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_pass
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  cache:
    image: memcached:alpine
    restart: unless-stopped

volumes:
  db_data:
  mongo_data:
  bsn_shared_data:
    external: true
