# DEV:
# docker compose build
# PROD:
# docker compose -f compose.yml -f compose.prod.yml build
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - bsn_shared_data:/var/www/bsn
    expose:
      - "9000"  # php-fpm
    env_file:
      - .env
    depends_on:
      - cache
      - mongo

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "44077:80"
    depends_on:
      - app
    volumes:
      - bsn_shared_data:/var/www/bsn

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongo_pass}
      MONGO_INITDB_DATABASE: ${MONGO_BASENAME:-app_db}
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017

  cache:
    image: memcached:alpine
    restart: unless-stopped

volumes:
  mongo_data:
  bsn_shared_data:
    external: true
