name: Build and push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_APP_NAME: montelibero/bsn_app
  IMAGE_WEB_NAME: montelibero/bsn_web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull previous WEB image for cache
        run: |
          docker pull $REGISTRY/$IMAGE_APP_NAME:latest || true

      - name: Build APP Docker image
        working-directory: ./app
        run: |
          docker build \
            --target prod \
            --cache-from $REGISTRY/$IMAGE_APP_NAME:latest \
            -t $REGISTRY/$IMAGE_APP_NAME:latest .

      - name: Push APP Docker image
        run: |
          docker push $REGISTRY/$IMAGE_APP_NAME:latest

      - name: Build WEB Docker image
        run: |
          docker build -f web/Dockerfile -t $REGISTRY/$IMAGE_WEB_NAME:latest .

      - name: Push WEB Docker image
        run: |
          docker push $REGISTRY/$IMAGE_WEB_NAME:latest

      - name: Notify Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d '{"chat_id": "-1003339919065", "text": "Docker image pushed to registry /info_bsn_app or /info_bsn_web"}'
          
